# Generated by Django 3.1.13 on 2021-10-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('token', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('default_fee', models.DecimalField(decimal_places=4, default=0.1, max_digits=30)),
                ('default_blockchain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchain')),
                ('native_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='token.token')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
