# Generated by Django 3.2.8 on 2021-10-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_load_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
