# Generated by Django 3.1.13 on 2021-10-10 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceNewToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=6, unique=True)),
                ('last_value', models.FloatField(null=True)),
                ('listing_day', models.DateTimeField(null=True)),
                ('announcement_seen', models.IntegerField(default=0, null=True)),
                ('discovered_method', models.CharField(choices=[('Binance Scrapper', 'Binance Scrapper'), ('Manual', 'Manual'), ('Other', 'Other')], default='Binance Scrapper', max_length=25)),
            ],
            options={
                'abstract': False,
                'unique_together': {('name', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='NewCoinConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scrapper_class_name', models.CharField(choices=[('ScrapBinanceModel', 'Binance Scrapper')], max_length=100, unique=True, verbose_name='Scrapper')),
                ('scrapping_interval', models.IntegerField(choices=[(5, 'Every 5 Mins'), (10, 'Every 10 Mins'), (15, 'Every 15 Mins'), (20, 'Every 20 Mins'), (30, 'Every 30 Mins'), (50, 'Every 50 Mins'), (60, 'Every 1 Hour'), (90, 'Every 1 And Half Hours'), (120, 'Every 2 Hours')], default=10)),
                ('activate_scheduler', models.BooleanField(default=False)),
                ('auto_clean', models.BooleanField(default=True, help_text='The tokens that are more than 2 days old will be promoted to regular tokens automatically')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
                ('task_auto_clean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_auto_clean', to='django_celery_beat.periodictask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
