# Generated by Django 3.2.8 on 2021-10-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_coin_bot', '0004_auto_20211019_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancenewtoken',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newcoinconfig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
