# Generated by Django 3.1.13 on 2021-09-18 12:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('default_fee', models.DecimalField(decimal_places=4, default=Decimal('0.1000000000000000055511151231257827021181583404541015625'), max_digits=30)),
                ('native_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token.token')),
            ],
        ),
    ]
