# Generated by Django 3.1.13 on 2021-09-18 13:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=250)),
                ('secret', models.CharField(max_length=250)),
                ('tld', models.CharField(default='com', max_length=10)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('default_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1000000000000000055511151231257827021181583404541015625'), max_digits=30)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
