# Generated by Django 3.1.13 on 2021-09-26 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '__first__'),
        ('token', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('api_key', models.CharField(max_length=250)),
                ('secret', models.CharField(max_length=250)),
                ('tld', models.CharField(default='com', max_length=10)),
                ('default_fee_rate', models.FloatField(default=0.1)),
                ('default', models.BooleanField(default=False, help_text='Default account to run fetch methods like token price update')),
                ('testnet', models.BooleanField(default=False)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('update_time', models.TimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token.token')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.ManyToManyField(through='account.AccountTokens', to='token.Token'),
        ),
        migrations.AddField(
            model_name='account',
            name='token_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_pair', to='token.token'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
