# Generated by Django 3.1.13 on 2021-09-18 13:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='default_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=30),
        ),
    ]
