# Generated by Django 3.1.13 on 2021-10-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCoinConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scrapping_interval', models.IntegerField(choices=[(5, 'Every 5 Mins'), (10, 'Every 10 Mins'), (15, 'Every 15 Mins'), (20, 'Every 20 Mins'), (30, 'Every 30 Mins'), (50, 'Every 50 Mins'), (60, 'Every 1 Hour'), (90, 'Every 1 And Half Hours'), (120, 'Every 2 Hours')], default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
