# Generated by Django 3.1.13 on 2021-10-02 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_auto_20211002_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCoinConfig',
        ),
    ]
