# Generated by Django 3.1.13 on 2021-09-26 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('symbol', models.CharField(max_length=6, unique=True)),
                ('blockchain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchain')),
                ('last_value', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('name', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('coin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token.coin')),
                ('token_type', models.CharField(choices=[('BEP-20', 'Bep 20'), ('ERC-20', 'Eth Erc 20'), ('ERC-223', 'Eth Erc 223'), ('ERC-721', 'Eth Erc 721'), ('ERC-777', 'Eth Erc 777'), ('ERC-820', 'Eth Erc 820'), ('ERC-1155', 'Eth Erc 1155'), ('SPL', 'Sol Spl'), ('EOSIO', 'Eos Eosio'), ('TZIP', 'Tezos Tzip'), ('NEP', 'Neo Nep'), ('OTHER', 'Other')], max_length=9)),
            ],
            bases=('token.coin',),
        ),
    ]
