# Generated by Django 3.1.13 on 2021-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_historicalaccounttokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='extended_exchange',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
