version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django-dev: &django-dev
    build:
      context: ..
      dockerfile: ./compose/local/django/Dockerfile
    image: vanir_local_django
    container_name: django-dev
    depends_on:
      - postgres-dev
      - mailhog-dev
    volumes:
      - ..:/app:z
    env_file:
      - ../.envs/.local/.django
      - ../.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres-dev:
    build:
      context: ..
      dockerfile: ./compose/postgres/Dockerfile
    image: vanir_local_postgres
    container_name: postgres-dev
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ../.envs/.local/.postgres

  docs-dev:
    image: vanir_local_docs
    container_name: docs-dev
    build:
      context: ..
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ../.envs/.local/.django
    volumes:
      - ../docs:/docs:z
      - ../config:/app/config:z
      - ../vanir:/app/vanir:z
    ports:
      - "7001:7000"
    command: /start-docs

  mailhog-dev:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog-dev
    ports:
      - "8026:8025"

  redis-dev:
    image: redis:6
    container_name: redis-dev

  celeryworker-dev:
    <<: *django-dev
    image: vanir_local_celeryworker
    container_name: celeryworker-dev
    depends_on:
      - redis-dev
      - postgres-dev
      - mailhog-dev
    ports: []
    command: /start-celeryworker

  celerybeat-dev:
    <<: *django-dev
    image: vanir_local_celerybeat
    container_name: celerybeat-dev
    depends_on:
      - redis-dev
      - postgres-dev
      - mailhog-dev
    ports: []
    command: /start-celerybeat

  flower-dev:
    <<: *django-dev
    image: vanir_local_flower
    container_name: flower-dev
    ports:
      - "5556:5555"
    command: /start-flower
