# Generated by Django 3.1.13 on 2021-09-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('token', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Side Buy'), ('SELL', 'Side Sell')], max_length=4)),
                ('orderType', models.CharField(choices=[('LIMIT', 'Order Type Limit'), ('MARKET', 'Order Type Market'), ('STOP_LOSS', 'Order Type Stop Loss'), ('STOP_LOSS_LIMIT', 'Order Type Stop Loss Limit'), ('TAKE_PROFIT', 'Order Type Take Profit'), ('TAKE_PROFIT_LIMIT', 'Order Type Take Profit Limit'), ('LIMIT_MAKER', 'Order Type Limit Maker')], max_length=20)),
                ('quoteOrderQty', models.FloatField(default=0.1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('token_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_from', to='token.token')),
                ('token_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_to', to='token.token')),
            ],
        ),
    ]
