# Generated by Django 3.1.13 on 2021-09-18 23:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20210918_1334'),
        ('token', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Side Buy'), ('SELL', 'Side Sell')], max_length=4)),
                ('quoteOrderQty', models.DecimalField(decimal_places=8, default=Decimal('0.1000000000000000055511151231257827021181583404541015625'), max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('token_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_from', to='token.token')),
                ('token_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_to', to='token.token')),
            ],
        ),
    ]
