# Generated by Django 3.1.13 on 2021-09-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderType',
            field=models.CharField(choices=[('LIMIT', 'Order Type Limit'), ('MARKET', 'Order Type Market'), ('STOP_LOSS', 'Order Type Stop Loss'), ('STOP_LOSS_LIMIT', 'Order Type Stop Loss Limit'), ('TAKE_PROFIT', 'Order Type Take Profit'), ('TAKE_PROFIT_LIMIT', 'Order Type Take Profit Limit'), ('LIMIT_MAKER', 'Order Type Limit Maker')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
