# Generated by Django 3.1.13 on 2021-10-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitorder',
            name='timeInForce',
            field=models.CharField(choices=[('GTC', 'Good Till Cancel'), ('IOC', 'Immediate Or Cancel'), ('FOK', 'Fill Or Kill')], default='GTC', help_text='Time in force indicates how long your order will remain active before it is executed or expired', max_length=4),
        ),
        migrations.AlterField(
            model_name='stoplossortakeprofitlimitorder',
            name='timeInForce',
            field=models.CharField(choices=[('GTC', 'Good Till Cancel'), ('IOC', 'Immediate Or Cancel'), ('FOK', 'Fill Or Kill')], default='GTC', help_text='Time in force indicates how long your order will remain active before it is executed or expired', max_length=4),
        ),
    ]
