# Generated by Django 3.1.13 on 2021-10-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211010_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitorder',
            name='side',
            field=models.CharField(choices=[('BUY', 'Side Buy'), ('SELL', 'Side Sell')], default='SELL', max_length=4),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='side',
            field=models.CharField(choices=[('BUY', 'Side Buy'), ('SELL', 'Side Sell')], default='SELL', max_length=4),
        ),
        migrations.AlterField(
            model_name='stoplossortakeprofitlimitorder',
            name='side',
            field=models.CharField(choices=[('BUY', 'Side Buy'), ('SELL', 'Side Sell')], default='SELL', max_length=4),
        ),
        migrations.AlterField(
            model_name='stoppriceorder',
            name='side',
            field=models.CharField(choices=[('BUY', 'Side Buy'), ('SELL', 'Side Sell')], default='SELL', max_length=4),
        ),
    ]
