# Generated by Django 3.1.13 on 2021-10-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_historicalaccounttokens'),
        ('order', '0003_auto_20211010_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitorder',
            name='account',
            field=models.ForeignKey(help_text='Select an account to populate automatically the tokens on Token from', on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='limitorder',
            name='order_id',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='account',
            field=models.ForeignKey(help_text='Select an account to populate automatically the tokens on Token from', on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='order_id',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='stoplossortakeprofitlimitorder',
            name='account',
            field=models.ForeignKey(help_text='Select an account to populate automatically the tokens on Token from', on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='stoplossortakeprofitlimitorder',
            name='order_id',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='stoppriceorder',
            name='account',
            field=models.ForeignKey(help_text='Select an account to populate automatically the tokens on Token from', on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='stoppriceorder',
            name='order_id',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
