# Generated by Django 3.1.13 on 2021-10-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('symbol', models.CharField(max_length=6, unique=True)),
                ('last_value', models.FloatField(null=True)),
                ('token_type', models.CharField(choices=[('BEP-20', 'Bep 20'), ('ERC-20', 'Eth Erc 20'), ('ERC-223', 'Eth Erc 223'), ('ERC-721', 'Eth Erc 721'), ('ERC-777', 'Eth Erc 777'), ('ERC-820', 'Eth Erc 820'), ('ERC-1155', 'Eth Erc 1155'), ('SPL', 'Sol Spl'), ('EOSIO', 'Eos Eosio'), ('TZIP', 'Tezos Tzip'), ('NEP', 'Neo Nep'), ('OTHER', 'Other')], max_length=9, null=True)),
            ],
            options={
                'unique_together': {('name', 'symbol')},
            },
        ),
    ]
