# Generated by Django 3.1.13 on 2021-10-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token', '0003_auto_20211010_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='last_value',
            field=models.FloatField(null=True, verbose_name='Last value in USDT'),
        ),
    ]
