log:
  level: INFO

entryPoints:
  web:
    address: ":80"

  flower:
    address: ":5555"

http:
  routers:
    django-web-router:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: vanir

    flower-secure-router:
      rule: "Host(`localhost`)"
      entryPoints:
        - flower
      service: flower

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    vanir:
      loadBalancer:
        servers:
          - url: http://vanir:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
