log:
  level: DEBUG

entryPoints:
  web:
    # http
    address: ":80"
#    http:
#      # https://docs.traefik.io/routing/entrypoints/#entrypoint
#      redirections:
#        entryPoint:
#          to: web-secure

  flower:
    address: ":5555"

#certificatesResolvers:
#  letsencrypt:
#    # https://docs.traefik.io/master/https/acme/#lets-encrypt
#    acme:
#      email: "guanana@example.com"
#      storage: /etc/traefik/acme/acme.json
#      # https://docs.traefik.io/master/https/acme/#httpchallenge
#      httpChallenge:
#        entryPoint: web

http:
  routers:
    django-web-router:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django
#      tls:
#        # https://docs.traefik.io/master/routing/routers/#certresolver
#        certResolver: letsencrypt

    flower-secure-router:
      rule: "Host(`localhost`)"
      entryPoints:
        - flower
      service: flower
#      tls:
#        # https://docs.traefik.io/master/routing/routers/#certresolver
#        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
