name: CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ main ]
    paths-ignore: [ "docs/**" ]


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Run all pre-commit hooks on all the files.

      - name: Install and Run Pre-commit
        uses: pre-commit/action@v2.0.3

  pytest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -s runner

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt -r requirements/production.txt

      - name: Run Tests
        env:
          DB: vanir
          DB_USER: runner
          DB_PASSWORD: ""
        run: |
          pytest --no-migrations --create-db --cov=./vanir/ --cov-report=xml

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: report/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true



