name: CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ main ]
    paths-ignore: [ "docs/**" ]


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Run all pre-commit hooks on all the files.

      - name: Install and Run Pre-commit
        uses: pre-commit/action@v2.0.3

  pytest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Redis
        run: |
          sudo apt-get update -y
          sudo apt-get install -y redis-server
          sudo systemctl start redis-server

      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -s runner
          sudo -u postgres createdb vanir
          sudo -u postgres psql -c "ALTER USER runner WITH PASSWORD 'supersafe';"
          sudo -u postgres psql -c "ALTER USER runner WITH SUPERUSER;"

      - uses: actions/cache@v3.0.11
        id: pycache
        with:
          path: ~/.cache/pip
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements/production.txt') }}-${{ hashFiles('requirements/local.txt') }}

      - name: Install Dependencies
        run: pip install --upgrade --upgrade-strategy eager -r requirements/local.txt -r requirements/production.txt

      - name: Run Tests
        env:
          DATABASE_URL: postgres://runner:supersafe@localhost/vanir
          REDIS_URL: redis://localhost:6379/0
          CELERY_BROKER_URL: ""
        run: |
          pytest --no-migrations --create-db --cov=./vanir/ --cov-report=xml

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true



