# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      #LOGIN
      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #METADATA
      - name: Extract metadata (tags, labels) for Vanir Docker
        id: meta_vanir
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vanir
            ghcr.io/${{ github.repository }}

      - name: Extract metadata (tags, labels) for Traefik Docker
        id: meta_traefik
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vanir-traefik
            ghcr.io/${{ github.repository }}-traefik

      - name: Extract metadata (tags, labels) for Postgres Docker
        id: meta_postgres
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vanir-postgres
            ghcr.io/${{ github.repository }}-postgres

      #BUILD
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: compose/production/django/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_vanir.outputs.tags }}
          labels: ${{ steps.meta_vanir.outputs.labels }}

      - name: Build and push traefik
        uses: docker/build-push-action@v2
        with:
          context: .
          file: compose/production/traefik/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_traefik.outputs.tags }}
          labels: ${{ steps.meta_traefik.outputs.labels }}

      - name: Build and push postgres
        uses: docker/build-push-action@v2
        with:
          context: .
          file: compose/postgres/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_postgres.outputs.tags }}
          labels: ${{ steps.meta_postgres.outputs.labels }}
